quotelist = ['Take time to take inventory of your life. Look in the mirror and hold yourself accountable. – David Goggins',
             'There is no better way to grow as a person than to do something you hate every day. – David Goggins',
             'Before you open your mouth and criticize someone, think about how you would feel if you were the person you were criticizing. – David Goggins',
             'Sometimes you must go to war with yourself to fix yourself. – David Goggins',
             'A lot of people put motivational quotes up on the wall and all they do is collect dust. Become what that quote says. Live it every day. – David Goggins',
             'Show people, don’t tell people! – David Goggins',
             'You may lose the battle of the morning but don’t lose the war of the day. – David Goggins',
             'Most of the amazing things in this world come from people who know how to turn their failure into a success. – David Goggins',
             'If you can see yourself doing something, you can do it. If you can’t see yourself doing it, usually you can’t achieve it. – David Goggins',
             'I like to see what I’m made of. I want to see if there is a limit to the human soul. – David Goggins',
             'Embrace the suck. Callus the mind. – David Goggins',
             'Motivation is crap. It comes and goes. Find what you’re passionate about. Then you can be driven. When you’re driven you don’t give a damn. – David Goggins',
             'A lot of us have these fears that you don’t want to fucking face. – David Goggins',
             'No one is going to help you. It’s you against yourself forever. – David Goggins',
             'If you’re a person who is stuck in life: figure out how to not be that person anymore. – David Goggins',
             'I started looking down on people who didn’t go HARD AS SHIT.  – David Goggins',
             'You’re going to have to suffer to go from here to there. Most people will never understand the journey.  – David Goggins',
             'If you’re not good enough don’t try something else – make yourself good enough. – David Goggins',
             'Whenever I’m stressed I get after it. I fix what’s bothering me. – David Goggins',
             'A lot of us when we have bad times even life, even the hardest person in the world, we forget how badass we are during that hard time – David Goggins',
             'I don’t close my mind to the fact that this can be done. – David Goggins',
             'You can read all the books you want. Unless you have a habit of surviving difficult scenarios, you’ll never thrive. – David Goggins',
             'People consuming self-help information look for magic words to change them. There aren’t any magic words. There is only your tolerance to suffering. – David Goggins',
             'The other side of quitting is a lifetime of regret. – David Goggins',
             'You’ve never fucking made it. – David Goggins',
             'A warrior is a mother-Fucker who says I’m here today. I’m here again tomorrow I’m going to be here the next day. – David Goggins',
             'Our greatest accomplishments produce mental trophies; not physical trophies. – David Goggins',
             'Put yourself in situations that suck. You’ll find yourself real quick. – David Goggins',
             '90 percent of your life will suck. – David Goggins',
             'A warrior is a person who puts no limits on themselves. – David Goggins',
             'Normal people are driven when their lives are good. The warrior is motivated when his life is bad, or good. – David Goggins',
             'Stop trying to be a champion. Be the fighter who refuses to go down from any setback he faces. – David Goggins',
             'You have to suffer. You have to make that a tattoo on your fucking brain. – David Goggins',
             'Become a man who detests mediocrity. – David Goggins',
             'Even the self-help gurus are afraid. Fear stops everyone. The few who move towards fear are the ones who change the world. – David Goggins',
             'Happiness increases with the amount of pain you’ve endured. – David Goggins',
             '"We live in an external world. Everything, you have to see it, touch it. If you can for the rest of your life, live inside yourself – to find greatness, you have to go inside” – David Goggins',
             '“It’s so easy to be great nowadays, because everyone else is weak.” – David Goggins',
             '“You went three hell weeks and finished two. One of the hells weeks, a guy died, it was so bad. Oh, you ARE a motherf***king badass” – David Goggins',
             'I said, “Who on this f***ing earth would be going right now? YOU ARE!” I believed it enough to where my body said, “he’s not gonna stop”. – David Goggins',
             '“I hated jumping out of airplanes, I hated shooting guns, I hated the job as a Navy SEAL – but I did it because I wanted to change myself." – David Goggins',
             '"Everything you do, I’m not really comfortable doing, but if you choose to go that route, to be a navy seal, you might as well go be the hardest motherf***er in the world." – David Goggins'
             '“I tried to do so many things to fit in. But when you look in the mirror, that’s the one person you can’t lie to.” – David Goggins ',
             '“Having lived the life I’ve lived, and seeing the other side, not being afraid to attack what was in front of me has made me happy.” – David Goggins ',
             'Most people who doubt you doubt you because they can never see themselves doing what you are trying to do. – David Goggins',
             'The path to success will leave you callused, bruised, and very tired. It will also leave you empowered. – David Goggins',
             'Don’t let your body or mind do exactly what it wants to do! Take control! – David Goggins',
             'Never let people who choose the path of least resistance steer you away from your chosen path of most resistance. – David Goggins',
             'Don’t be the person that looks at the weather report the night before to decide what you are going to do the next day. – David Goggins',
             'The only thing more contagious than a good attitude is a bad one. – David Goggins',
             'Don’t get mad at others because life is kicking your ass. – David Goggins',
             'Success is based off of your willingness to work your ass off no matter what obstacles are in your way. – David Goggins',
             'Be true to whoever or whatever you are and wear it like a badge of honor. Fit in with one person and one person only: yourself. – David Goggins',
             'Don’t limit expectations of yourself and settle for anything less than what you are truly capable of achieving. – David Goggins',
             'We live in a world where a lot of people need goals, motivation, and a lot of other words to get started. It’s just a big excuse to not get started. – David Goggins',
             'Life isn’t always about doing the things we like to do. It’s about doing things we have to do. – David Goggins',
             'Even if you are hurting, never let your competition see the look of defeat or even vulnerability on your face. – David Goggins',
             'When you fall down, focus on the solution, not the problem. You might quit or fail 100 times. Keep that clear picture of where you want to be. – David Goggins',
             'Teach yourself that it isn’t ok to take the easy way out. Make sure you are bothered by the things you set out to do but did not complete or make time for in the day. – David Goggins',
             'You can will yourself to do almost anything you want. – David Goggins',
             'When you think you’re done, you’re only at 40 percent of your body’s capability. – David Goggins',
             'High achievement doesn’t require inborn talent. It requires working your ass off. Period. – David Goggins',
             'We have the ability to make very easy things seem impossible. Stop losing the mind game against yourself. – David Goggins',
             'Comfort zones: If you like in one too long…that becomes your norm. Get comfortable being uncomfortable. – David Goggins',
             'Most people who are criticizing and judging haven’t even tried what you failed at. – David Goggins',
             'Whoever says you can’t develop mental toughness or anything else doesn’t truly understand the human mind or the human spirit. – David Goggins',
             'Stop thinking and do something. – David Goggins',
             ]
